In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print("dtype:", x3.dtype)

dtype: int32


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [7]:
x = np.arange(10)
x



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [9]:

x[:5]  # first five element

array([0, 1, 2, 3, 4])

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[:3,:3]

array([[3, 5, 2],
       [7, 6, 8],
       [1, 6, 7]])

In [12]:
import numpy as np
theta = np.linspace(0, np.pi, 3)

In [13]:
x = np.arange(10)
y = np.empty(10)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
